### ISSUE TITLE
Tightening up installation and maybe I'm confused?

### ISSUE THREAD

**Issue by codefriar** [PetriPod/PetriPod#5]
@evanmn I'm assigning this to you, but @all feel free to chime in. What follows is a condensed version of your wiki doc, with some questions along the way. 

`curl -sfL https://get.k3s.io | sh -s - --no-deploy=traefik` - This worked without error. However...
`sudo kubectl get pods --all-namespaces` immediately afterwards shows *nothing*. For whatever reason it took ~90 seconds before `get pods` returned anything. 

I skipped installing kubectl on my client machine because it's shipped with docker for mac.

Helm installed just fine. However! Helm allowed me to add repositories without sudo, and threw an error when I tried to use it to install traefik. had to re-add the repos with sudo before I could install traefik. Also had to run `export KUBECONFIG=/etc/rancher/k3s/k3s.yaml` before I could install traefik.

I installed Traefik with this 
```
helm install \
    --namespace=kube-system \
    --set providers.redis.endpoints=redis.database.svc.cluster.local:6379 \
    --set providers.redis.password=use_a_secret \
    --set persistence.enabled=true \
    traefik \
    traefik/traefik
```

At this point, I do get a 404 for anything on my cluster. (yay?)

Next i created a file `tingress.yml` on my host and filled it with:

```yml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.tardis.k3s`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
```

Then I ran `kubectl apply -f tingress.yml' which gave me `ingressroute.traefik.containo.us/traefik-dashboard created` (Yay?)

I did the same with the k3s dashboard: (kdash.yml)

```yml
kind: IngressRouteTCP
metadata:
  name: kubernetes-dashboard
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`k3s.tardis.k3s`)
    services:
    - name: kubernetes-dashboard
      port: 443
``` 

At this point, I naively? thought I should be able to hit dashboard.tardis.k3s or k3s.tardis.k3s in the browser. I tried both https: and http:. Http: gives me an immediate 404 for both here. Https:// gives me a cert warning, then a 404. 

Am I wrong to think I should be able to access the dashboard at this point?

I deployed the whoami service, as you specified it. I only changed the domain name to tardis.k3s

After a `kubectl apply -f whoami.yml` I hit http://tardis.k3s/tls and it worked! However https://tardis.k3s/tls results in a 404 after the cert warning is dismissed. 

So then I installed Redis, as directed, and that went fine. I was able to use the redis cli and set the LE data. I even ran the `set traefik/ports/traefik/expose=true` however, that didn't expose the traefik dashboard ... What am I doing wrong?

**Comment by ghost** [comment]
I'll look into this in more detail in the morning, but here are my immediate conclusions.

1. K3s install creates a systemd service and starts it, takes a while for pods to start after the script exits. Afaik this is normal

2. Traefik dash should come up, I'm not sure

3. Didn't specify in document but you need to install the k8s dashboard, it dosent come by default.

4. Might be that it couldn't issue a certificate? I've only tested on an actual domain with certificate.

**Comment by ghost** [comment]
Just another note, as a demo in my doc I used different entrypoints for different services. For the kdash.yml, it is set as entrypoints `websecure`. In the helm chat it is specified that it should only listen on :443 (https). And the opposite for the tdash.yaml (:80, http).

**Comment by codefriar** [comment]
Yeah, I figured the websecure / http meant the ingress route would only apply to the given port that matches but I tested http and https both. 

I've set my client computer (laptop)'s /etc/host file with a direct mapping for traefik.tardis.k3s to the ip of the machine and, I know traefik is working - whoami works - but the dashboard... I'm missing something.

**Comment by ghost** [comment]
I've most likely forgot to add a detail to the wiki. Am on mobile now but will check my setup in the morning

**Comment by ghost** [comment]
@codefriar 

I've just tested this following my documentation to the letter, and I have a typo for the traefik dashboard. There are two closing parenthesis for the host rule.

It is also better to install redis first before traefik so it can grab config on install. Some things like persistance are still required for the install command. in the helm command. I'm not sure what I did before to have the k8s dashboard work with no hassle, but now traefik can't talk to the dashboard (most likely tls related). 

I'll update the wiki once I figure out the k8s dashboard.

**Comment by codefriar** [comment]
Thanks for the update!

**Comment by codefriar** [comment]
@evanmn - is this the section you're referring to?

```yml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.evan.im`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
```
